export enum ActionType {
  ADDING_TERM = "Adding a term",
  DELETING_TERM = "Deleting a term",
  ADDING_KEYWORD = "Adding a Keyword",
  DELETING_KEYWORD = "Deleting a Keyword",
  DELETING_KEYWORD_IMAGE = "Deleting a Keyword image",
  TOGGLE_KEYWORD_IMAGE = "Toggle a Keyword image",
  SET_KEYWORD_IMAGE = "Set a Keyword image",
  SET_SEARCHED_IMAGES = "Set searched images",
  SET_CURRENT_SET_ID = "Set current set id",
  ADDING_SET = "Adding a set",
  DELETING_SET = "Deleting a set",
  SET_TERM_INFO = "Set term info",
  SET_SET_INFO = "Set set info",
  SET_KEYWORD_INFO = "Set keyword info",
  SAVE_CURRENT_SET = "Save current set",
  COPY_SAVED_SET = "Copy saved set",
}
